from classes.form_components.section.section import Section


class ReportExpenditureExacution(Section):
    def __init__(self):
        super().__init__()

    def grantee_vat_declaration(self):
        return self.create_chapter(
            components=[
                self.create_component(
                    component_type="radio",
                    name="granteeVatDeclaration",
                    copy_from="applicantVatDeclaration",
                    read_only=True,
                    required=True,
                    options=[
                        "Wnioskodawca JEST płatnikiem VAT, dlatego kwoty zamieszczone w kosztorysie we wniosku to KWOTY NETTO",
                        "Wnioskodawca NIE JEST płatnikiem VAT, dlatego kwoty zamieszczone w kosztorysie wniosku to KWOTY BRUTTO"
                    ]
                )
            ]
        )

    def expenses_information_incurred_in_implementing_the_project(self):
        return self.create_chapter(
            title="A. Informacja o wydatkach poniesionych przy wykonaniu przedsięwzięcia",
            class_list={
                "main": [
                    "table-4",
                    "grid",
                    "grid-cols-4"
                ],
                "sub": [
                    "table-4__col"
                ]
            },
            components=[
                self.create_component(
                    component_type="text",
                    mask="fund",
                    label="Całkowity koszt realizacji przedsięwzięcia",
                    name="reportingCostsTotal",
                    calculation_rules=[
                        self.calculation_rule.copy_value(
                            from_name="costActualTotalSum"
                        )
                    ],
                    validators=[
                        self.validator.related_sum_validator(
                            field_names=[
                                "budgetTotalCurrentSumAmount"
                            ]
                        )
                    ],
                    read_only=True,
                    unit="PLN",
                    class_list=[
                        "userInput-bg-red",
                        "default-margin",
                        "label-center"
                    ]
                ),
                self.create_component(
                    component_type="text",
                    mask="fund",
                    label="w tym koszty pokryte ze środków PISF",
                    name="reportingCostsPisfSupport",
                    calculation_rules=[
                        self.calculation_rule.copy_value(
                            from_name="costActualSupportPisfSum"
                        )
                    ],
                    read_only=True,
                    unit="PLN",
                    class_list=[
                        "default-margin",
                        "label-center"
                    ]
                ),
                self.create_component(
                    component_type="text",
                    mask="fund",
                    label="w tym środki własne",
                    name="reportingCostsOwnFunds",
                    calculation_rules=[
                        self.calculation_rule.copy_value(
                            from_name="budgetInputOwnFundsCurrentAmount"
                        )
                    ],
                    read_only=True,
                    unit="PLN",
                    class_list=[
                        "default-margin",
                        "label-center"
                    ]
                ),
                self.create_component(
                    component_type="text",
                    mask="fund",
                    label="w tym inne środki",
                    name="reportingCostsOtherFunds",
                    calculation_rules=[
                        #     TODO
                    ],
                    read_only=True,
                    unit="PLN",
                    class_list=[
                        "default-margin",
                        "label-center"
                    ]
                )
            ]
        )

    def cost_estimate_by_source_of_financing(self):
        return self.create_chapter(
            title="2. Kosztorys ze względu na źródło finansowania",
            class_list={
                "sub": [
                    "table-invoice-top"
                ]
            },
            components=[
                self.create_chapter(
                    components=[
                        self.create_component(
                            component_type="header",
                            name="description",
                            value="Zestawienie to stanowi porównanie kosztów planowanych z faktycznie poniesionymi. Uwaga: procentowy wkład dotacji PISF w finalnym budżecie przedsięwzięcia nie może przekroczyć wkładu zakładanego (określonego w umowie). Jeżeli faktycznie poniesiony koszt całkowity przedsięwzięcia okazał się niższy od planowanego lub Beneficjent nie wykorzystał całej dotacji, należy dokonać zwrotu na rachunek PISF i dostarczyć wraz z raportem potwierdzenie przelewu. Nr rachunku PISF: Banku Gospodarstwa Krajowego Beneficjenci krajowi: 91 1130 1017 0020 1234 1320 0016, Beneficjenci zagraniczni: PL 91 1130 1017 0020 1234 1320 0016 SWIFT: GOSKPLPW."
                        )
                    ]
                ),
                self.create_chapter(
                    class_list=[
                        "grid",
                        "grid-cols-12",
                        "table-header"
                    ],
                    components=[
                        self.create_component(
                            component_type="header",
                            name="plannedCostSecond",
                            value="Koszt planowany",
                            class_list=[
                                "col-start-5",
                                "col-span-4",
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="alreadySpentSecond",
                            value="Koszt poniesiony",
                            class_list=[
                                "col-span-4",
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="costTypeSecond",
                            value="Źródło finansowania",
                            class_list=[
                                "col-span-4",
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="plannedPln",
                            value="PLN",
                            class_list=[
                                "col-span-2",
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="plannedShare",
                            value="%",
                            class_list=[
                                "col-span-2",
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="actualPln",
                            value="PLN",
                            class_list=[
                                "col-span-2",
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="actualShare",
                            value="%",
                            class_list=[
                                "col-span-2",
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        )
                    ]
                ),
                self.create_chapter(
                    title="Koszty pokryte z dofinansowania PISF",
                    class_list={
                        "main": [
                            "table-4",
                            "grid",
                            "grid-cols-6",
                            "no-title",
                            "chapter-bg-red"
                        ],
                        "sub": [
                            "table-4__col"
                        ]
                    },
                    components=[
                        self.create_component(
                            component_type="header",
                            name="costPISF",
                            value="Koszty pokryte z dofinansowania PISF",
                            class_list=[
                                "col-span-2",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Preliminarz",
                            name="budgetInputPisfSupportAmount",
                            read_only=True,
                            copy_from="costRequestPisfSum",
                            unit="PLN",
                            class_list=[
                                "no-label"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Preliminarz: udział w całym budżecie",
                            name="budgetInputPisfSupportShare",
                            read_only=True,
                            copy_from="costRequestPisfSumShare",
                            unit="%",
                            class_list=[
                                "no-label"
                            ],
                            calculation_rules=[
                                self.calculation_rule.share_calculator(
                                    dividend_field="budgetInputPisfSupportAmount",
                                    divisor_field="reportingCostsTotal"
                                )
                            ],
                            validators=[
                                self.validator.related_share_validator(
                                    dividend="budgetInputPisfSupportAmount",
                                    divisor="reportingCostsTotal"
                                )
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Koszty bieżące",
                            name="budgetInputPisfSupportCurrentAmount",
                            calculation_rules=[
                                self.calculation_rule.copy_value(
                                    from_name="costActualSupportPisfSum"
                                )
                            ],
                            read_only=True,
                            unit="PLN",
                            class_list=[
                                "no-label"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Koszty bieżące: udział w całym budżecie",
                            name="budgetInputPisfSupportCurrentShare",
                            read_only=True,
                            unit="%",
                            class_list=[
                                "no-label"
                            ],
                            calculation_rules=[
                                self.calculation_rule.share_calculator(
                                    dividend_field="budgetInputPisfSupportCurrentAmount",
                                    divisor_field="reportingCostsTotal"
                                )
                            ],
                            validators=[
                                self.validator.related_share_validator(
                                    dividend="budgetInputPisfSupportCurrentAmount",
                                    divisor="reportingCostsTotal"
                                ),
                                self.validator.range_validator(
                                    max_value=100,
                                    message="Procentowy wkład dotacji PISF w finalnym budżecie przedsięwzięcia nie może przekroczyć wkładu zakładanego (określonego w umowie)."
                                )
                            ]
                        )
                    ]
                ),
                self.create_chapter(
                    title="Środki własne",
                    class_list={
                        "main": [
                            "table-4",
                            "grid",
                            "grid-cols-6",
                            "no-title",
                            "chapter-bg-grey"
                        ],
                        "sub": [
                            "table-4__col"
                        ]
                    },
                    components=[
                        self.create_component(
                            component_type="header",
                            name="ownFunds",
                            value="Środki własne",
                            class_list=[
                                "col-span-2",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Preliminarz",
                            name="budgetInputOwnFundsAmount",
                            read_only=True,
                            copy_from="costOwnFundsSum",
                            unit="PLN",
                            class_list=[
                                "no-label"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Preliminarz: udział w całym budżecie",
                            name="budgetInputOwnFundsShare",
                            read_only=True,
                            calculation_rules=[
                                self.calculation_rule.share_calculator(
                                    dividend_field="budgetInputOwnFundsAmount",
                                    divisor_field="reportingCostsTotal"
                                )
                            ],
                            validators=[
                                self.validator.related_share_validator(
                                    dividend="budgetInputOwnFundsAmount",
                                    divisor="reportingCostsTotal"
                                )
                            ],
                            unit="%",
                            class_list=[
                                "no-label"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Koszty bieżące",
                            name="budgetInputOwnFundsCurrentAmount",
                            unit="PLN",
                            class_list=[
                                "no-label"
                            ],
                            validators=[
                                self.validator.related_fraction_lte_validator(
                                    field_name="costActualTotalSum",
                                    ratio=0.1,
                                    message="Minimalny wkład własny wnioskodawcy powinien wynosić 10% całości budżetu przedsięwzięcia."
                                )
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Koszty bieżące: udział w całym budżecie",
                            name="budgetInputOwnFundsCurrentShare",
                            read_only=True,
                            unit="%",
                            class_list=[
                                "no-label"
                            ],
                            calculation_rules=[
                                self.calculation_rule.share_calculator(
                                    dividend_field="budgetInputOwnFundsCurrentAmount",
                                    divisor_field="reportingCostsTotal"
                                )
                            ],
                            validators=[
                                self.validator.related_share_validator(
                                    dividend="budgetInputOwnFundsCurrentAmount",
                                    divisor="reportingCostsTotal"
                                )
                            ]
                        )
                    ]
                ),
                self.create_chapter(
                    title="Środki partnerów prywatnych i publicznych łacznie",
                    class_list={
                        "main": [
                            "table-4",
                            "grid",
                            "grid-cols-6",
                            "no-title",
                            "chapter-bg-grey"
                        ],
                        "sub": [
                            "table-4__col"
                        ]
                    },
                    components=[
                        self.create_component(
                            component_type="header",
                            name="otherPartners",
                            value="Środki partnerów prywatnych i publicznych łącznie",
                            class_list=[
                                "col-span-2",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Preliminarz",
                            name="budgetInputAllPartnersAmount",
                            read_only=True,
                            unit="PLN",
                            class_list=[
                                "no-label"
                            ],
                            calculation_rules=[
                                self.calculation_rule.dynamic_sum_inputs(
                                    fields=[
                                        "budgetInputPartnersSponsorsAmount",
                                        "budgetInputPublicSourcesAmount"
                                    ]
                                )
                            ],
                            validators=[
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "budgetInputPartnersSponsorsAmount",
                                        "budgetInputPublicSourcesAmount"
                                    ]
                                )
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Preliminarz: udział w całym budżecie",
                            name="budgetInputAllPartnersShare",
                            read_only=True,
                            calculation_rules=[
                                self.calculation_rule.share_calculator(
                                    dividend_field="budgetInputAllPartnersAmount",
                                    divisor_field="reportingCostsTotal"
                                )
                            ],
                            validators=[
                                self.validator.related_share_validator(
                                    dividend="budgetInputAllPartnersAmount",
                                    divisor="reportingCostsTotal"
                                )
                            ],
                            unit="%",
                            class_list=[
                                "no-label"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Koszty bieżące",
                            name="budgetInputAllPartnersCurrentAmount",
                            unit="PLN",
                            class_list=[
                                "no-label"
                            ],
                            read_only=True,
                            calculation_rules=[
                                self.calculation_rule.dynamic_sum_inputs(
                                    fields=[
                                        "budgetInputPartnersSponsorsCurrentAmount",
                                        "budgetInputPublicSourcesCurrentAmount"
                                    ]
                                )
                            ],
                            validators=[
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "budgetInputPartnersSponsorsCurrentAmount",
                                        "budgetInputPublicSourcesCurrentAmount"
                                    ]
                                )
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Koszty bieżące: udział w całym budżecie",
                            name="budgetInputAllPartnersCurrentShare",
                            read_only=True,
                            unit="%",
                            class_list=[
                                "no-label"
                            ],
                            calculation_rules=[
                                self.calculation_rule.share_calculator(
                                    dividend_field="budgetInputAllPartnersCurrentAmount",
                                    divisor_field="reportingCostsTotal"
                                )
                            ],
                            validators=[
                                self.validator.related_share_validator(
                                    dividend="budgetInputAllPartnersCurrentAmount",
                                    divisor="reportingCostsTotal"
                                )
                            ]
                        )
                    ]
                ),
                self.create_chapter(
                    title="Środki innych partnerów/sponsorów",
                    class_list={
                        "sub": [
                            "table-4-top"
                        ],
                        "main": [
                            "no-title",
                            "chapter-bg-grey"
                        ]
                    },
                    components=[
                        self.create_chapter(
                            title="Razem",
                            class_list={
                                "main": [
                                    "table-4",
                                    "grid",
                                    "grid-cols-6",
                                    "no-title"
                                ],
                                "sub": [
                                    "table-4__col"
                                ]
                            },
                            components=[
                                self.create_component(
                                    component_type="header",
                                    name="totalPartnersSponsors",
                                    value="Środki innych partnerów/sponsorów łącznie",
                                    class_list=[
                                        "col-span-2",
                                        "displayNoneFrontend"
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Preliminarz",
                                    name="budgetInputPartnersSponsorsAmount",
                                    read_only=True,
                                    unit="PLN",
                                    class_list=[
                                        "no-label"
                                    ],
                                    calculation_rules=[
                                        self.calculation_rule.dynamic_sum_inputs(
                                            fields=[
                                                "budgetInputPartnerSponsorAmount"
                                            ]
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_sum_validator(
                                            field_names=[
                                                "budgetInputPartnerSponsorAmount"
                                            ]
                                        )
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Preliminarz: udział w całym budżecie",
                                    name="budgetInputPartnersSponsorsShare",
                                    read_only=True,
                                    calculation_rules=[
                                        self.calculation_rule.share_calculator(
                                            dividend_field="budgetInputPartnersSponsorsAmount",
                                            divisor_field="reportingCostsTotal"
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_share_validator(
                                            dividend="budgetInputPartnersSponsorsAmount",
                                            divisor="reportingCostsTotal"
                                        )
                                    ],
                                    unit="%",
                                    class_list=[
                                        "no-label"
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Koszty bieżące",
                                    name="budgetInputPartnersSponsorsCurrentAmount",
                                    unit="PLN",
                                    class_list=[
                                        "no-label"
                                    ],
                                    read_only=True,
                                    calculation_rules=[
                                        self.calculation_rule.dynamic_sum_inputs(
                                            fields=[
                                                "budgetInputPartnerSponsorCurrentAmount"
                                            ]
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_sum_validator(
                                            field_names=[
                                                "budgetInputPartnerSponsorCurrentAmount"
                                            ]
                                        )
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Koszty bieżące: udział w całym budżecie",
                                    name="budgetInputPartnersSponsorsCurrentShare",
                                    read_only=True,
                                    unit="%",
                                    class_list=[
                                        "no-label"
                                    ],
                                    calculation_rules=[
                                        self.calculation_rule.share_calculator(
                                            dividend_field="budgetInputPartnersSponsorsCurrentAmount",
                                            divisor_field="reportingCostsTotal"
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_share_validator(
                                            dividend="budgetInputPartnersSponsorsCurrentAmount",
                                            divisor="reportingCostsTotal"
                                        )
                                    ]
                                )
                            ]
                        ),
                        self.create_chapter(
                            is_paginated=True,
                            multiple_forms_rules={
                                "minCount": 1,
                                "maxCount": 20
                            },
                            class_list={
                                "sub": [
                                    "table-4-top"
                                ]
                            },
                            components=[
                                self.create_chapter(
                                    title="Partner lub sponsor",
                                    class_list={
                                        "main": [
                                            "table-4",
                                            "table-invoice",
                                            "grid",
                                            "grid-cols-6",
                                        ],
                                        "sub": [
                                            "table-4-2__col"
                                        ]
                                    },
                                    components=[
                                        self.create_component(
                                            component_type="text",
                                            label="Nazwa partnera lub sponsora",
                                            name="partnerSponsorName",
                                            validators=[
                                                self.validator.length_validator(max_value=100)
                                            ],
                                            class_list=[
                                                "col-start-2",
                                                "no-label"
                                            ]
                                        ),
                                        self.create_component(
                                            component_type="text",
                                            mask="fund",
                                            label="Preliminarz",
                                            name="budgetInputPartnerSponsorAmount",
                                            read_only=True,
                                            unit="PLN",
                                            class_list=[
                                                "no-label"
                                            ]
                                        ),
                                        self.create_component(
                                            component_type="text",
                                            mask="fund",
                                            label="Preliminarz: udział w całym budżecie",
                                            name="budgetInputPartnerSponsorShare",
                                            read_only=True,
                                            calculation_rules=[
                                                self.calculation_rule.share_calculator(
                                                    dividend_field="budgetInputPartnerSponsorAmount",
                                                    divisor_field="reportingCostsTotal"
                                                )
                                            ],
                                            validators=[
                                                self.validator.related_share_validator(
                                                    dividend="budgetInputPartnerSponsorAmount",
                                                    divisor="reportingCostsTotal"
                                                )
                                            ],
                                            unit="%",
                                            class_list=[
                                                "no-label"
                                            ]
                                        ),
                                        self.create_component(
                                            component_type="text",
                                            mask="fund",
                                            label="Koszty bieżące",
                                            name="budgetInputPartnerSponsorCurrentAmount",
                                            unit="PLN",
                                            class_list=[
                                                "no-label"
                                            ]
                                        ),
                                        self.create_component(
                                            component_type="text",
                                            mask="fund",
                                            label="Koszty bieżące: udział w całym budżecie",
                                            name="budgetInputPartnerSponsorCurrentShare",
                                            read_only=True,
                                            unit="%",
                                            class_list=[
                                                "no-label"
                                            ],
                                            calculation_rules=[
                                                self.calculation_rule.share_calculator(
                                                    dividend_field="budgetInputPartnerSponsorCurrentAmount",
                                                    divisor_field="reportingCostsTotal"
                                                )
                                            ],
                                            validators=[
                                                self.validator.related_share_validator(
                                                    dividend="budgetInputPartnerSponsorCurrentAmount",
                                                    divisor="reportingCostsTotal"
                                                )
                                            ]
                                        )
                                    ]
                                )
                            ]
                        )
                    ]
                ),
                self.create_chapter(
                    title="Pozostałe źródła publiczne",
                    class_list={
                        "sub": [
                            "table-4-top"
                        ],
                        "main": [
                            "no-title",
                            "chapter-bg-grey"
                        ]
                    },
                    components=[
                        self.create_chapter(
                            title="Razem",
                            class_list={
                                "main": [
                                    "table-4",
                                    "grid",
                                    "grid-cols-6",
                                    "no-title"
                                ],
                                "sub": [
                                    "table-4__col"
                                ]
                            },
                            components=[
                                self.create_component(
                                    component_type="header",
                                    name="totalPublicSources",
                                    value="Pozostałe źródła publiczne łącznie",
                                    class_list=[
                                        "col-span-2",
                                        "displayNoneFrontend"
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Preliminarz",
                                    name="budgetInputPublicSourcesAmount",
                                    read_only=True,
                                    unit="PLN",
                                    class_list=[
                                        "no-label"
                                    ],
                                    calculation_rules=[
                                        self.calculation_rule.dynamic_sum_inputs(
                                            fields=[
                                                "budgetInputPublicSourceAmount"
                                            ]
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_sum_validator(
                                            field_names=[
                                                "budgetInputPublicSourceAmount"
                                            ]
                                        )
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Preliminarz: udział w całym budżecie",
                                    name="budgetInputPublicSourcesShare",
                                    read_only=True,
                                    calculation_rules=[
                                        self.calculation_rule.share_calculator(
                                            dividend_field="budgetInputPublicSourcesAmount",
                                            divisor_field="reportingCostsTotal"
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_share_validator(
                                            dividend="budgetInputPublicSourcesAmount",
                                            divisor="reportingCostsTotal"
                                        )
                                    ],
                                    unit="%",
                                    class_list=[
                                        "no-label"
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Koszty bieżące",
                                    name="budgetInputPublicSourcesCurrentAmount",
                                    unit="PLN",
                                    class_list=[
                                        "no-label"
                                    ],
                                    read_only=True,
                                    calculation_rules=[
                                        self.calculation_rule.dynamic_sum_inputs(
                                            fields=[
                                                "budgetInputPublicSourceCurrentAmount"
                                            ]
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_sum_validator(
                                            field_names=[
                                                "budgetInputPublicSourceCurrentAmount"
                                            ]
                                        )
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Koszty bieżące: udział w całym budżecie",
                                    name="budgetInputPublicSourcesCurrentShare",
                                    read_only=True,
                                    unit="%",
                                    class_list=[
                                        "no-label"
                                    ],
                                    calculation_rules=[
                                        self.calculation_rule.share_calculator(
                                            dividend_field="budgetInputPublicSourcesCurrentAmount",
                                            divisor_field="reportingCostsTotal"
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_share_validator(
                                            dividend="budgetInputPublicSourcesCurrentAmount",
                                            divisor="reportingCostsTotal"
                                        )
                                    ]
                                )
                            ]
                        ),
                        self.create_chapter(
                            is_paginated=True,
                            multiple_forms_rules={
                                "minCount": 1,
                                "maxCount": 20
                            },
                            class_list={
                                "sub": [
                                    "table-4-top"
                                ]
                            },
                            components=[
                                self.create_chapter(
                                    title="Źródła publiczne",
                                    class_list={
                                        "main": [
                                            "table-4",
                                            "table-invoice",
                                            "grid",
                                            "grid-cols-6",
                                        ],
                                        "sub": [
                                            "table-4-2__col"
                                        ]
                                    },
                                    components=[
                                        self.create_component(
                                            component_type="text",
                                            label="Nazwa partnera lub sponsora",
                                            name="publicSourceName",
                                            validators=[
                                                self.validator.length_validator(max_value=100)
                                            ],
                                            class_list=[
                                                "col-start-2",
                                                "no-label"
                                            ]
                                        ),
                                        self.create_component(
                                            component_type="text",
                                            mask="fund",
                                            label="Preliminarz",
                                            name="budgetInputPublicSourceAmount",
                                            read_only=True,
                                            unit="PLN",
                                            class_list=[
                                                "no-label"
                                            ]
                                        ),
                                        self.create_component(
                                            component_type="text",
                                            mask="fund",
                                            label="Preliminarz: udział w całym budżecie",
                                            name="budgetInputPublicSourceShare",
                                            read_only=True,
                                            calculation_rules=[
                                                self.calculation_rule.share_calculator(
                                                    dividend_field="budgetInputPublicSourceAmount",
                                                    divisor_field="reportingCostsTotal"
                                                )
                                            ],
                                            validators=[
                                                self.validator.related_share_validator(
                                                    dividend="budgetInputPublicSourceAmount",
                                                    divisor="reportingCostsTotal"
                                                )
                                            ],
                                            unit="%",
                                            class_list=[
                                                "no-label"
                                            ]
                                        ),
                                        self.create_component(
                                            component_type="text",
                                            mask="fund",
                                            label="Koszty bieżące",
                                            name="budgetInputPublicSourceCurrentAmount",
                                            unit="PLN",
                                            class_list=[
                                                "no-label"
                                            ]
                                        ),
                                        self.create_component(
                                            component_type="text",
                                            mask="fund",
                                            label="Koszty bieżące: udział w całym budżecie",
                                            name="budgetInputPublicSourceCurrentShare",
                                            read_only=True,
                                            unit="%",
                                            class_list=[
                                                "no-label"
                                            ],
                                            calculation_rules=[
                                                self.calculation_rule.share_calculator(
                                                    dividend_field="budgetInputPublicSourceCurrentAmount",
                                                    divisor_field="reportingCostsTotal"
                                                )
                                            ],
                                            validators=[
                                                self.validator.related_share_validator(
                                                    dividend="budgetInputPublicSourceCurrentAmount",
                                                    divisor="reportingCostsTotal"
                                                )
                                            ]
                                        )
                                    ]
                                )
                            ]
                        )
                    ]
                ),
                self.create_chapter(
                    title="Źródła finansowania ogółem",
                    class_list={
                        "main": [
                            "table-4",
                            "grid",
                            "grid-cols-6",
                            "no-title",
                            "chapter-bg-grey"
                        ],
                        "sub": [
                            "table-4__col"
                        ]
                    },
                    components=[
                        self.create_component(
                            component_type="header",
                            name="fundingSourcesOverall",
                            value="Źródła finansowania ogółem",
                            class_list=[
                                "col-span-2",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Preliminarz",
                            name="budgetTotalSumAmount",
                            read_only=True,
                            unit="PLN",
                            class_list=[
                                "no-label"
                            ],
                            calculation_rules=[
                                self.calculation_rule.dynamic_sum_inputs(
                                    fields=[
                                        "budgetInputPisfSupportAmount",
                                        "budgetInputOwnFundsAmount",
                                        "budgetInputAllPartnersAmount"
                                    ]
                                )
                            ],
                            validators=[
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "budgetInputPisfSupportAmount",
                                        "budgetInputOwnFundsAmount",
                                        "budgetInputAllPartnersAmount"
                                    ]
                                ),
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "costTotalSum"
                                    ]
                                )
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Preliminarz: udział w całym budżecie",
                            name="budgetTotalSumShare",
                            read_only=True,
                            calculation_rules=[
                                self.calculation_rule.share_calculator(
                                    dividend_field="budgetTotalSumAmount",
                                    divisor_field="budgetTotalSumAmount"
                                )
                            ],
                            validators=[
                                self.validator.related_share_validator(
                                    dividend="budgetTotalSumAmount",
                                    divisor="budgetTotalSumAmount"
                                )
                            ],
                            unit="%",
                            class_list=[
                                "no-label"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Koszty bieżące",
                            name="budgetTotalCurrentSumAmount",
                            unit="PLN",
                            class_list=[
                                "no-label"
                            ],
                            read_only=True,
                            calculation_rules=[
                                self.calculation_rule.dynamic_sum_inputs(
                                    fields=[
                                        "budgetInputPisfSupportCurrentAmount",
                                        "budgetInputOwnFundsCurrentAmount",
                                        "budgetInputAllPartnersCurrentAmount"
                                    ]
                                )
                            ],
                            validators=[
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "budgetInputPisfSupportCurrentAmount",
                                        "budgetInputOwnFundsCurrentAmount",
                                        "budgetInputAllPartnersCurrentAmount"
                                    ]
                                ),
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "costActualTotalSum"
                                    ]
                                )
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Koszty bieżące: udział w całym budżecie",
                            name="budgetTotalCurrentSumShare",
                            read_only=True,
                            unit="%",
                            class_list=[
                                "no-label"
                            ],
                            calculation_rules=[
                                self.calculation_rule.share_calculator(
                                    dividend_field="budgetTotalCurrentSumAmount",
                                    divisor_field="reportingCostsTotal"
                                )
                            ],
                            validators=[
                                self.validator.related_share_validator(
                                    dividend="budgetTotalCurrentSumAmount",
                                    divisor="reportingCostsTotal"
                                )
                            ]
                        )
                    ]
                ),
                self.create_chapter(
                    components=[
                        self.create_component(
                            component_type="header",
                            name="budgetComments",
                            value="Wyjaśnienie dotyczące różnic pomiędzy kosztem planowanym a poniesionym",
                            class_list=[
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="textarea",
                            label="Uwagi",
                            name="budgetComments",
                            validators=[
                                self.validator.length_validator(max_value=10000)
                            ],
                            class_list=[
                                "no-label"
                            ]
                        )
                    ]
                )
            ]
        )

    def list_of_bills_and_invoices(self):
        return self.create_chapter(
            title="B. Zestawienie faktur/rachunków",
            class_list={
                "sub": [
                    "table-invoice-top"
                ]
            },
            components=[
                self.create_chapter(
                    components=[
                        self.create_component(
                            component_type="header",
                            name="invoiceDescription",
                            value="Zestawienie to spis wszystkich faktur/rachunków/biletów, które dotyczą przedsięwzięcia i zostały pokryte z dofinansowania PISF. Spis zawierać powinien: rodzaj dokumentu (faktura/rachunek), nr faktury/rachunku (w przypadku rachunku należy podać jego nr i datę oraz podać nr i datę umowy, której dotyczy), datę wystawienia dokumentu, nazwę wydatku (rodzaj towaru/usługi), wysokość wydatkowanej kwoty ze wskazaniem części, w jakiej została ona pokryta z dofinansowania PISF. Uwaga: Każda z faktur/rachunków opłaconych z otrzymanego dofinansowania powinna być opatrzona na odwrocie pieczęcią Beneficjenta oraz zawierać sporządzony w sposób trwały opis zawierający informacje: z jakich środków wydatkowana kwota została pokryta oraz jakie było przeznaczenie zakupionych towarów, usług lub innego rodzaju opłaconej należności. Informacja ta powinna być podpisana przez osobę odpowiedzialną za sprawy dotyczące rozliczeń finansowych Beneficjenta. Do raportu nie zalicza się faktur/rachunków, które należy przechowywać zgodnie z obowiązującymi przepisami i udostępniać podczas przeprowadzanych czynności kontrolnych. W przypadku faktur za akredytacje, noclegi, bilety lub umów o dzieło należy podać imię i nazwisko osoby, której dotyczą (z funkcji PISF mogą to być tylko osoby wskazane w umowie) oraz numer i datę zawartej umowy o dofinansowanie PISF (w wersji elektronicznej). Do zakończenia zadania przedsięwzięcia określonego w harmonogramie stanowiącym załącznik nr 1/1A do Umowy. Przeliczeń z waluty obcej na PLN należy dokonywać dla każdej pozycji osobno, wg średniego kursu NBP z dnia poprzedzającego dzień wystawienia faktury. Uwzględniaj należy wartość przelicznika do 4. miejsca po przecinku, a otrzymaną wartość w PLN – zaokrąglić do 2. miejsca po przecinku. Kolejność wpisywania faktur powinna być taka sama jak kolejność pozycji kosztorysu."
                        )
                    ]
                ),
                self.create_chapter(
                    class_list=[
                        "grid",
                        "grid-cols-12",
                        "table-header"
                    ],
                    components=[
                        self.create_component(
                            component_type="header",
                            name="invoiceTotalCost",
                            value="Kwota całkowita",
                            class_list=[
                                "text-center",
                                "col-start-9",
                                "col-span-2",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoicePISFRefund",
                            value="W tym z dofinansowania PISF",
                            class_list=[
                                "text-center",
                                "col-start-11",
                                "col-span-2",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoiceLp",
                            value="Lp.",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoiceNumber",
                            value="Nr i nazwa dokument księgowego",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoiceCurrency",
                            value="Waluta PLN",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoicePositionNumber",
                            value="Nr pozycji kosztorysu",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoiceIssuedDate",
                            value="Data wystawienia",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoicePaymentDate",
                            value="Data zapłaty",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoiceDesc",
                            value="Waluta",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="invoicePriceNBP",
                            value="Średni kurs NBP",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="totalInvoiceOtherCurrency",
                            value="W walucie obcej",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="totalInvoicePLN",
                            value="PLN",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="supportInvoiceOtherCurrency",
                            value="W walucie obcej",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                        self.create_component(
                            component_type="header",
                            name="supportInvoicePLN",
                            value="PLN",
                            class_list=[
                                "text-center",
                                "displayNoneFrontend"
                            ]
                        ),
                    ]
                ),
                self.create_chapter(
                    multiple_forms_rules={
                        "minCount": 1,
                        "maxCount": 60
                    },
                    is_paginated=True,
                    class_list={
                        "sub": [
                            "table-invoice-top"
                        ],
                        "main": [
                            "no-title",
                            "swappable-bg",
                            "lp-table"
                        ]
                    },
                    components=[
                        self.create_chapter(
                            title="Faktura/rachunek",
                            class_list={
                                "sub": [
                                    "table-invoice__col"
                                ],
                                "main": [
                                    "table-invoice",
                                    "grid",
                                    "grid-cols-12"
                                ]
                            },
                            components=[
                                self.create_component(
                                    component_type="textarea",
                                    label="Lp.",
                                    name="lp-number-invoice",
                                    class_list=[
                                        "displayNoneFrontend",
                                        "lp-number",
                                        "no-label"
                                    ]
                                ),
                                self.create_component(
                                    component_type="textarea",
                                    label="Nazwa i opis wydatku",
                                    name="costExpenditureDesc",
                                    validators=[
                                        self.validator.length_validator(
                                            max_value=200
                                        )
                                    ],
                                    required=True,
                                    class_list=[
                                        "col-span-11",
                                        "text-bold",
                                        "no-label",
                                        "text-left"
                                    ]
                                ),
                                self.create_component(
                                    component_type="textarea",
                                    label="Rodzaj i numer dokumentu księgowego",
                                    name="accountingDocTypeNum",
                                    validators=[
                                        self.validator.length_validator(
                                            max_value=150
                                        )
                                    ],
                                    required=True,
                                    class_list=[
                                        "table-invoice__full",
                                        "no-label",
                                        "col-start-2"
                                    ]
                                ),
                                self.create_component(
                                    component_type="checkbox",
                                    label="Waluta PLN",
                                    name="expenditureInPln",
                                    help_text="Zaznacz jeśli wydatek poniesiono w złotych.",
                                    class_list=[
                                        "no-label"
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    label="Numer pozycji kosztorysu",
                                    name="costEstimateItemNum",
                                    validators=[
                                        self.validator.length_validator(
                                            max_value=10
                                        )
                                    ],
                                    required=True,
                                    class_list=[
                                        "no-label"
                                    ]
                                ),
                                self.create_component(
                                    component_type="date",
                                    label="Data wystawienia",
                                    name="accountingDocDateIssued",
                                    validators=[
                                        self.validator.related_date_gte_validator(
                                            field_name="taskDateStart",
                                            message="Data wystawienia nie może być wcześniejsza niż data wpłynięcia wniosku."
                                        ),
                                        self.validator.related_date_lte_validator(
                                            field_name="taskDateEnd",
                                            message="Data wystawienia nie może być późniejsza niż data zakończenia przedsięwzięcia"
                                        )
                                    ],
                                    required=True,
                                    class_list=[
                                        "no-label"
                                    ]
                                ),
                                self.create_component(
                                    component_type="date",
                                    label="Data zapłaty",
                                    name="costPaymentDate",
                                    validators=[
                                        self.validator.related_date_gte_validator(
                                            field_name="taskDateStart",
                                            message="Data zapłaty nie może być wcześniejsza niż data wpłynięcia wniosku."
                                        ),
                                        self.validator.related_date_lte_validator(
                                            field_name="taskDateEnd",
                                            message="Data zapłaty nie może być późniejsza niż data zakończenia przedsięwzięcia"
                                        )
                                    ],
                                    required=True,
                                    class_list=[
                                        "no-label"
                                    ]
                                ),
                                self.create_component(
                                    component_type="currency",
                                    label="Waluta",
                                    name="costCurrency",
                                    class_list=[
                                        "no-label",
                                        "table-1-2"
                                    ],
                                    required=True
                                ),
                                self.create_component(
                                    component_type="number",
                                    label="Kurs średni NBP",
                                    name="costCurrencyNbpExchRate",
                                    calculation_rules=[
                                        self.calculation_rule.get_nbp_currency(
                                            date_field="accountingDocDateIssued",
                                            currency_field="costCurrency",
                                        )
                                    ],
                                    validators=[
                                        self.validator.length_validator(
                                            max_value=20
                                        )
                                    ],
                                    read_only=True,
                                    class_list=[
                                        "no-label",
                                        "table-1-2"
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Kwota całkowita w walucie obcej",
                                    name="costInCurrency",
                                    class_list=[
                                        "no-label",
                                        "table-1-2"
                                    ]
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="Kwota całkowita w PLN",
                                    name="costInPln",
                                    class_list=[
                                        "no-label"
                                    ],
                                    read_only=True,
                                    calculation_rules=[
                                        self.calculation_rule.local_multiply_inputs(
                                            fields=[
                                                "costInCurrency",
                                                "costCurrencyNbpExchRate"
                                            ]
                                        )
                                    ],
                                    validators=[
                                        self.validator.related_local_multiplication_validator(
                                            field_names=[
                                                "costInCurrency",
                                                "costCurrencyNbpExchRate"
                                            ]
                                        )
                                    ],
                                    unit="PLN"
                                ),
                                self.create_component(
                                    component_type="text",
                                    mask="fund",
                                    label="W tym ze środków pochodzących z dofinansowania PISF w PLN",
                                    name="costInPlnPisf",
                                    required=True,
                                    class_list=[
                                        "no-label"
                                    ],
                                    unit="PLN"
                                )
                            ]
                        )
                    ]
                ),
                self.create_chapter(
                    title="Łącznie PLN",
                    class_list={
                        "main": [
                            "table-2-sum",
                            "grid",
                            "grid-cols-4",
                            "no-title"
                        ],
                        "sub": [
                            "table-2-sum__col"
                        ]
                    },
                    components=[
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="Suma wydatków w PLN",
                            name="costInPlnTotalSum",
                            calculation_rules=[
                                self.calculation_rule.dynamic_sum_inputs(
                                    fields=[
                                        "costInPln"
                                    ]
                                )
                            ],
                            validators=[
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "costInPln"
                                    ]
                                )
                            ],
                            read_only=True,
                            unit="PLN",
                            class_list=[
                                "default-margin",
                                "col-start-3",
                                "userInput-border"
                            ]
                        ),
                        self.create_component(
                            component_type="text",
                            mask="fund",
                            label="W tym z dofinansowania PISF w PLN",
                            name="costInPlnPisfTogether",
                            calculation_rules=[
                                self.calculation_rule.dynamic_sum_inputs(
                                    fields=[
                                        "costInPlnPisf"
                                    ]
                                )
                            ],
                            validators=[
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "costInPlnPisf"
                                    ]
                                ),
                                self.validator.related_sum_validator(
                                    field_names=[
                                        "reportingCostsPisfSupport"
                                    ]
                                )
                            ],
                            read_only=True,
                            unit="PLN",
                            class_list=[
                                "default-margin",
                                "userInput-border"
                            ]
                        )
                    ]
                )
            ]
        )
